import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import { createBaseConfig } from "@classtown/config/eslint/base";

export default [
  ...createBaseConfig(import.meta.dirname),
  ...nextCoreWebVitals,
  // Auto-generated by `supabase gen types` — not hand-written, not worth
  // linting for style.
  { ignores: ["src/lib/supabase/database.types.ts"] },
];
