packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: true
  msgpackr-extract: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@supabase/auth-js@2.115.0'
  - '@supabase/functions-js@2.115.0'
  - '@supabase/postgrest-js@2.115.0'
  - '@supabase/realtime-js@2.115.0'
  - '@supabase/storage-js@2.115.0'
  - '@supabase/supabase-js@2.115.0'
  - '@types/react-dom@19.2.7'
  - '@vitest/mocker@5.0.0'
  - '@vitest/spy@5.0.0'
  - vitest@5.0.0
