import { createBaseConfig } from "@classtown/config/eslint/base";

const config = [
  ...createBaseConfig(import.meta.dirname),
  // Generated by `supabase gen types typescript` — never hand-edited, so it is
  // not held to the handwritten source's rules.
  { ignores: ["src/database.types.ts"] },
];

export default config;
